### ISSUE TITLE
Subscription icon does not show in VSIXed extension

### ISSUE THREAD

**Issue by itowlson** [Azure/vscode-aks-tools#11]
With the new login/display experience, subscriptions are meant to now have a 'key' icon.  When running the extension from source, this appears correctly.  But when packaged as a VSIX (or downloaded from the marketplace), the key does _not_ appear and there is a blank gap.  This is cosmetic but would be nice to figure out.

Tentatively assigning this to @philliphoff but if you don't have bandwidth then please assign it back to me!

**Comment by philliphoff** [comment]
How strange!  I'll take a look.
