### ISSUE TITLE
Extension can't find `grep` when installed in a windows OS

### ISSUE THREAD

**Issue by sonofhammer** [Azure/vscode-aks-tools#124]
I installed the extension on a windows 10 machine that doesn't have `grep` installed. 

I got the following warning:

> Azure Service Operator api-resources command failed with following error: 'grep' is not recognized as an internal or external command, operable program or batch file. .

**Comment by Tatsinnit** [comment]
Thank you @sonofhammer for noticing this, we will fix this and release it as part of `0.0.18` for vscode. We will loop back once release in marketplace is done. Really appreciate for this. 🙏☕️
