### ISSUE TITLE
Bring extension out of preview.

### ISSUE THREAD

**Issue by Tatsinnit** [Azure/vscode-aks-tools#131]
Hiya Guys, 

Writing this issue as tracking issue for any thoughts / idea which might suggest otherwise, we are planing to drop `Preview` out of this extension which means that in this line within package.json will be gone https://github.com/Azure/vscode-aks-tools/blob/master/package.json#L6 along with all the preview reference if any fro documentation and the version will sit at `1.0.0` 

Thank you for taking time and taking a look at this, ❤️🙏☕️ cc: @rzhang628 , @squillace , @itowlson and @peterbom please plus one if you all agree.

**Comment by itowlson** [comment]
👍 🎉 🚀 💯 ❤️

**Comment by rzhang628** [comment]
I love this feature! Please move forward :)
