### ISSUE TITLE
Can't login to cluster

### ISSUE THREAD

**Issue by shaygover** [Azure/vscode-aks-tools#146]
Hi,

For some reason, vscode says That "No clouds registered, Click here....".
AKS is installed and was working fine a few months ago.
If I downgrade AKS plugin version to 1.1 it sometimes work.

I can sign in to Azure so that part works.

Ideas?

**Comment by Tatsinnit** [comment]
Hiya @shaygover, Thanks for this ping, The only way I can replicate if I uninstall my actual AKS extension, so I am guessing you see this screen below, have you downloaded the AKS Extension form market place, because if you click on that link it sill take you through the extensions cloud provider page:

* AKS Extension Marketplace link: https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-aks-tools  

Hope below helps, and after extension install please do restart vscode and see if it does the enabling for you. ☕️🙏

<img width="326" alt="Screen Shot 2022-07-19 at 2 11 45 PM" src="https://user-images.githubusercontent.com/6233295/179649325-647c8c0c-9cbd-419e-b386-4cc8138227e2.png">


<img width="977" alt="Screen Shot 2022-07-19 at 2 13 56 PM" src="https://user-images.githubusercontent.com/6233295/179649484-7f0ec88a-d443-4aa1-b5b6-afc0aa6f9b05.png">

**Comment by shaygover** [comment]
It's installed.

**Comment by shaygover** [comment]
v1.69.1
On Linux. Tried reinstalling.

**Comment by Tatsinnit** [comment]
Thank you so much @shaygover. 

I am still not able to replicate this, can you share any error, vscode logs files? What O/S are you operating on? If there are specific steps I can do to reproduce this then it will be really helpful please.

Once extension is installed, and you restart the vscode the extension is still not installed so have you checked the extension manager if there is some sort of permission not letting your local to download this extension. (Apologies but this is just a idea in dark without having to replicate this at my end)

I am also cc-ing couple of other folks to try it out in other O/S cc: @rzhang628 and @peterbom inc are they can see this happening.

Hoping we can help you more with any further details which can help us to diagnose this issue. Thank you 🙏

**Comment by itowlson** [comment]
@Tatsinnit I gave it a quick try on WSL.  I didn't drill in (because I no longer have an account), but an Azure entry appeared in Cloud Explorer for me with k8s extension 1.3.10 and AKS 1.2.0.  Not very helpful I'm afraid...!

**Comment by shaygover** [comment]
I'll try to completely uninstall and then reinstall.
In the meantime, have any dependencies changed in the last 6 months?
I might have something missing.

**Comment by Tatsinnit** [comment]
Hiya @shaygover , thank you and sound like a plan. 

The AKS extension is child extension of Kubernetes extension and under the **dependencies** section you can check (in case you are missing anything) (might be az-cli?)

* link to Kubernetes extension- https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools

Thanks,
^Tats

**Comment by shaygover** [comment]
No. I meant new libraries it might require and such, not other extensions.

**Comment by Tatsinnit** [comment]
> No. I meant new libraries it might require and such, not other extensions.
> […](#)

Hiya @shaygover , to avoid further misunderstanding, I am not able to get the libraries reference? are you building this extension for contributio? Or are you consuming this extension as a tool? 

Thank you.

**Comment by shaygover** [comment]
Consuming but the builder might've missed something.

**Comment by Tatsinnit** [comment]
> Consuming but the builder might've missed something.
> […](#)

AFAIK - the extension gets downloaded as VSIX - OPC (open packaging convention), I don’t honk any extra external libraries will be required. 

Just for share: Here is a nice read about anatomy of VSIX https://docs.microsoft.com/en-us/visualstudio/extensibility/anatomy-of-a-vsix-package?view=vs-2022

might be worth checking that you have Kubernetes extension installed, az-cli and aks extension. 

Will wait for more info in case you have replication steps.

rhank you so much 🙏☕️

**Comment by itowlson** [comment]
@Tatsinnit I think Shay must have the k8s extension installed or they wouldn't see the Clouds pane at all.

@shaygover As per one of Tats' earlier messages, the logs may be the best way to diagnose this - it feels like the extension is either not loading or is having some sort of race condition (your comment that 1.1 works "sometimes" makes me wonder if a race could be the problem).  Failures like this are logged, I think, to the `Output > Logs (Extension Host)` pane - have a look there and see if anything jumps out at you.

It may also be possible to tell if the extension is loading by trying to run an AKS command from the Command Palette (if there are any, I'm not sure) and seeing if it does anything.

Finally, if you are willing, you could try uninstalling the marketplace build, cloning the source code, and running it under the debugger.  This would give you more of a chance to track what's happening during activation.  I'm happy to run through how to do this if you'd like to try it (and I'm sure folks like Tats and Peter are too).

(Tats, do forgive me for butting in!)

**Comment by shaygover** [comment]
Same after reinstall of the same version. It worked for a few moments with v1.63 and older extension versions. When I tried to update to new version, it stopped working. Will attempt again to find the stable versions.
Also note that I'm unable to install AKS from the search, I can't find it. Had to install from file.
Nothing in the logs.

How do I run the code under the debugger?

**Comment by shaygover** [comment]
Using v1.64.1 and Azure Account v0.10.1, I can login.
However, I couldn't list nodes.

But a least now there was something useful in the logs:
the azure auth plugin is deprecated in v1.22+, unavailable in v1.25+; use https://github.com/Azure/kubelogin instead.

So I installed that and run

```
export KUBECONFIG=/home/<user>/.kube/config

kubelogin convert-kubeconfig

kubectl get no

```

And now it working, still with v1.64.1. Will attempt to upgrade to latest later.

**Comment by shaygover** [comment]
v1.69.2 working.
Closing.
Thanks everyone!
