### ISSUE TITLE
Ability to delete pods under a namespace selected in VS Code for AKS Cluster

### ISSUE THREAD

**Issue by godrejwadia** [Azure/vscode-aks-tools#219]
**Many of us are not used to running kubectl commands to manage cluster operations.**
It takes lot of time to find pod names by using get commands then run the delete command over it.
If this extension for AKS in VS Code has a dropdown showing pod names
We can easily right click on it and do delete operation.

**Manual process is as below as of now**
```
kubectl config set-context my-context
kubectl get pods -n my-namespace
```

After getting pod name copy it and use in below command
`kubectl delete pod mypod-123abc -n my-namespace`

**Comment by Tatsinnit** [comment]
Thank you so much @godrejwadia for this request. very cool and I think this is possible in the current extension space, via kubernetes extension which is key dependency for the AKS Extension.

User can select `Merge to Kubeconfig` functionality which will set the current cluster context for the kubernetes extension and then you can `delete pod`.

Screen flow:

> Firstly use `Merge to Kubeconfig` which will get your cluster appear int the `kubernetes` cluster explorer window. 

<img width="414" alt="Screenshot 2023-07-27 at 7 48 02 AM 1" src="https://github.com/Azure/vscode-aks-tools/assets/6233295/d70ae6de-ecb9-4f2d-adc8-a8c997593538">

> Then, navigate to `Workloads` -> `Pods` which will show all the pods under that cluster and from there, upon right-clicking select `delete now`.

<img width="365" alt="Screenshot 2023-07-27 at 7 48 42 AM" src="https://github.com/Azure/vscode-aks-tools/assets/6233295/b706d606-901a-4300-99f6-be83a5d31a4c">

Thank you so much for this request, and please let us know if this is something you are looking for.

**Comment by Tatsinnit** [comment]
Thank you all, closing this issue for now, as there is no actionable instance, the delete pod is explained above, as to how it can be done. Please feel free to re-open with further idea @godrejwadia, thank you so much for this and looking forward for anything else if we can help with. 🙏☕️
