### ISSUE TITLE
Rename `master` to `main` branch for this repo

### ISSUE THREAD

**Issue by Tatsinnit** [Azure/vscode-aks-tools#232]
This PR is to open the tracking item for changing the branch name from `master` to `main`. Anyone has any preferences or thought against? Thank you so much.

* https://github.com/github/renaming#renaming-the-default-branch-from-master 
* How to rename: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch 

fyi and for thoughts: @peterbom, @qpetraroia , @gambtho ❤️🙏☕️🔔

```[tasklist]
### Tasks
- [ ] Rename branch from master to main.
```

**Comment by gambtho** [comment]
if it doesn't badly break any automation, seems like a easy win

**Comment by Tatsinnit** [comment]
🔔🔔🥷 This is done now, all user in their local fork need to do is follow instruction which will appear like this:

First do. this in your fork:

<img width="717" alt="Screenshot 2023-09-29 at 12 06 58 PM" src="https://github.com/Azure/vscode-aks-tools/assets/6233295/b59977a5-b2b4-47f4-b891-af9af4697551">

Then:

<img width="576" alt="Screenshot 2023-09-29 at 12 15 07 PM" src="https://github.com/Azure/vscode-aks-tools/assets/6233295/c37f0b7d-96c4-4918-b0b1-e216e5f96210">
