### ISSUE TITLE
Add the AKS logo to the AKS Extension welcome page

### ISSUE THREAD

**Issue by qpetraroia** [Azure/vscode-aks-tools#237]

**Comment by Tatsinnit** [comment]
Thank you so much for this, Its an interesting one, I am sure anyone can correct me but this icon of vscode at top of `welcome` page is not changeable:

helpful link: https://code.visualstudio.com/api/ux-guidelines/walkthroughs

<img width="378" alt="Screenshot 2023-10-03 at 2 58 48 PM" src="https://github.com/Azure/vscode-aks-tools/assets/6233295/84532002-0a03-4513-86dc-7ca689eef91a">

**Comment by Tatsinnit** [comment]
Further to add here is the OpenShift walkthrough as sample which has no title icon custom, the other one is webview:

<img width="1192" alt="Screenshot 2023-10-05 at 2 41 12 PM" src="https://github.com/Azure/vscode-aks-tools/assets/6233295/8c44a5de-207e-46ac-8339-012d136955c7">

<img width="1175" alt="Screenshot 2023-10-05 at 2 41 48 PM" src="https://github.com/Azure/vscode-aks-tools/assets/6233295/5cd5c679-e999-4300-98e6-8aeafa813d63">

**Comment by qpetraroia** [comment]
Interesting! Looks like walkthroughs must have the vscode logo. Good to close on my side. Thanks for investigating!
