### ISSUE TITLE
opening https dashboard link with certificate invalid and asking for token

### ISSUE THREAD

**Issue by mohamedfasil** [Azure/vscode-aks-tools#24]
Since today, this is opening https://localhost:10000 and asking for token or kubeconfig to login

**Comment by Tatsinnit** [comment]
Hey, @mohamedfasil do you have consistent replication steps (Which might help to re-pro, if this behaviour relates to this extension or just the login to the account takes you to localhost)? Also, what was the behaviour previously, is this relating to your login for the azure account? Essentially anything else which might help in digging deeper to help us better understand if this is specific to extension issue or beyond it?

Thanks heaps,

**Comment by itowlson** [comment]
This sounds like it may be this issue from the core k8s extension: https://github.com/Azure/vscode-kubernetes-tools/issues/617 (I don't think there's a dashboard command in the AKS extension).  @mohamedfasil did you by any chance recently upgrade the AKS cluster?

cc @bnookala

**Comment by mohamedfasil** [comment]
Hey @itowlson, yes that was the problem, closing this issue

**Comment by itowlson** [comment]
@Tatsinnit would you be willing to look at the core extension issue?  It is one of the places where we had to inject an AKS-specific workaround, I think, so within your bailiwick I think!

**Comment by Tatsinnit** [comment]
Cool, Sounds good, @itowlson :) Also I have not touch that side of the extension so might as well see how exactly whole things fit together. ⛩️ 👍
