### ISSUE TITLE
Compare two or more aks clusters or any resources for their metadata and properties.

### ISSUE THREAD

**Issue by sprab** [Azure/vscode-aks-tools#347]
**Is your feature request related to a problem? Please describe.**
New feature.

**Mention what platform you want to support the new feature**
VScode, portal and/or external.

**Describe the solution you'd like**
A feature to compare two or more clusters for their metadata, properties/attributes that will allow us to draw conclusions while troubleshooting issues as what is different between two clusters (working or non-working scenarios).

**Describe alternatives you've considered**
There are no alternate solutions apart from being manually compare them side by side on two different windows.

**Additional context**

**Comment by Tatsinnit** [comment]
**Docs**: Get Jason and then use `vscode` - `diff`.

* https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/get?view=rest-aks-2023-08-01&tabs=HTTP

Implementation level details: (High level) 

####  Drop -1: Compare 2 cluster - aka - 2 cluster compare.

* U/X of some Sort (I can add pic latter of a sketch)
* On hit homage, we do `get` or `rest operation` on the both the clusters like: https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/get?view=rest-aks-2023-08-01&tabs=HTTP 
    * Then formulate the `temp` files for both cluster.
* Then use `code.diff` docs here : https://code.visualstudio.com/api/references/commands

Thanks heaps,  fyi => @peterbom and @sprab 

#### Sample only below.

<img width="1238" alt="Screenshot 2023-12-04 at 2 00 25 PM" src="https://github.com/Azure/vscode-aks-tools/assets/6233295/7f318727-3e87-4c2d-a54b-7f351b8f5c8d">

<img width="1770" alt="Screenshot 2023-12-04 at 1 56 05 PM" src="https://github.com/Azure/vscode-aks-tools/assets/6233295/32b6ddc4-3fbd-4a65-81e6-5c28228f5adc">

**Comment by Tatsinnit** [comment]
Thank you @sprab , I Think we can move this to discussion for the further enhancement aspects you have and the internal work which shows the next level of this enhancement to be discussed along with wider folks like @peterbom. 

I thought I will drop this fyi comment as #363 is now merged as phase-0 to attain the quick way to compare 2 clusters.
