### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by FusionArc** [Azure/vscode-aks-tools#49]
- Issue Type: `Bug`
- Extension Name: `vscode-aks-tools`
- Extension Version: `0.0.8`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.50.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by FusionArc** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 179,
		"activateCallTime": 0,
		"activateResolvedTime": 22459,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "mindaro.mindaro",
				"_lower": "mindaro.mindaro"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Failed to get the current context from the kubeconfig: No kubeconfig file found at path C:\\Users\\davec\\.kube\\config"
		}
	]
}
```

**Comment by itowlson** [comment]
+ @daniv-msft because it looks like Mindaro/Bridge to Kubernetes is involved here

**Comment by daniv-msft** [comment]
Thanks @itowlson. I confirm this error is coming from https://github.com/Microsoft/mindaro.

@FusionArc Could you please clarify what is wrong from your perspective?
The error in itself seems legitimate to me, if no kubeconfig file is present in the target location.
If your kubeconfig file is stored in another location, feel free to update the current target location through the `Kubernetes: Set Kubeconfig` command in VS Code.

If you don't have a local kubeconfig file and don't plan to have one, feel free to also hide the status bar item (right click > Hide) or disable the `Bridge to Kubernetes` extension, which is owning this status bar item.

Please let me know if you have any questions or if I misunderstood your scenario.

**Comment by Tatsinnit** [comment]
Thank you @daniv-msft ! Hello @FusionArc ,seems like best place to share detail will be against this repository with more details, https://github.com/Microsoft/mindaro. new version of Bridge to Kubernetes earlier this week. Thanks heaps,

cc: @itowlson
