### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by bariscankurtkaya** [Azure/vscode-aks-tools#52]
- Issue Type: `Bug`
- Extension Name: `vscode-aks-tools`
- Extension Version: `0.0.8`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 14497,
		"activateCallTime": 0,
		"activateResolvedTime": 6,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "mindaro.mindaro",
				"_lower": "mindaro.mindaro"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by Tatsinnit** [comment]
💡 Thanks, + hello @daniv-msft because it looks like Mindaro/Bridge to Kubernetes is involved here. cc:@itowlson

**Comment by daniv-msft** [comment]
Thanks @bariscankurtkaya for logging this issue, and @Tatsinnit for looping me in.

@bariscankurtkaya Could you please clarify the issue you encountered? As there are no errors mentioned in the bug, it's not very clear to me what goes wrong.

@Tatsinnit FYI, we realized recently that we still kept a VS Code dependency in Bridge to Kubernetes on the AKS extension, whereas we're not AKS specific anymore. We'll remove this dependency with the next release, so you shouldn't get this kind of issues anymore. Of course, we'll still keep our dependency on the Kubernetes extension.

**Comment by Tatsinnit** [comment]
Thanks @bariscankurtkaya , further,  thanks @daniv-msft for the details, as there is no actionable information and this specific issue is related to the `Mindaro/Bridge to k8s` I will close this issue for now, and in case there is any further information which is relates to this extension please feel free to re-open it. 

Also I noticed a similar issue here which seems like related to `Mindaro/bridge to k8s` https://github.com/Azure/vscode-kubernetes-tools/issues/844 
 
cc: @itowlson , thank you all.
