### ISSUE TITLE
Update Inspektor Gadget version

### ISSUE THREAD

**Issue by blanquicet** [Azure/vscode-aks-tools#524]
The Inspektor Gadget version used by default is 0.19.0, but next week Inspektor Gadget will already release v0.26.0. I suggest updating it to provide the new features released in all those versions.

**Comment by Tatsinnit** [comment]
Nice! Thank you so much @blanquicet , ❤️🙏☕️  Updated to the latest available but regularly we will keep eye on latest versions and update accordingly, since Ita taken care by #525 will close it for now, but please do let us know if there is anything else.
