### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Adesoji1** [Azure/vscode-aks-tools#53]
- Issue Type: `Bug`
- Extension Name: `vscode-aks-tools`
- Extension Version: `0.0.8`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.52.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 8700,
		"activateCallTime": 0,
		"activateResolvedTime": 42,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "azuredevspaces.azds",
				"_lower": "azuredevspaces.azds"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "\\\\?\\c:\\Users\\Sortol\\.vscode\\extensions\\vsciot-vscode.vscode-iot-device-cube-0.3.0\\out\\node_modules\\usb-detection\\build\\Release\\detection.node is not a valid Win32 application.\r\n\\\\?\\c:\\Users\\Sortol\\.vscode\\extensions\\vsciot-vscode.vscode-iot-device-cube-0.3.0\\out\\node_modules\\usb-detection\\build\\Release\\detection.node"
		},
		{
			"name": "Error",
			"message": "\\\\?\\c:\\Users\\Sortol\\.vscode\\extensions\\vsciot-vscode.vscode-iot-workbench-0.16.0\\node_modules\\usb-detection\\build\\Release\\detection.node is not a valid Win32 application.\r\n\\\\?\\c:\\Users\\Sortol\\.vscode\\extensions\\vsciot-vscode.vscode-iot-workbench-0.16.0\\node_modules\\usb-detection\\build\\Release\\detection.node"
		}
	]
}
```

**Comment by Tatsinnit** [comment]
💡 Thank you, + hello @daniv-msft for any recommendation I believe it is from `azds` shich is this: https://marketplace.visualstudio.com/items?itemName=azuredevspaces.azds the recommendation looks like Bridge to Kubernetes,  here. cc:@itowlson

**Comment by daniv-msft** [comment]
@Adesoji1 Thank you for logging this issue. This error seems indeed to be coming from the Azure Dev Spaces extension, which is being retired. Could you please uninstall this extension?
If you still need to debug Kubernetes services from VS Code, please have a look at https://marketplace.visualstudio.com/items?itemName=mindaro.mindaro which is the successor of Azure Dev Spaces.

@Tatsinnit Thank you for looping me in. On a side note, we released our new version of Bridge to Kubernetes earlier this week and we don't have a dependency on AKS there anymore.

**Comment by Tatsinnit** [comment]
Thank you so much @daniv-msft cool, as recommended, thank you @Adesoji1 seems like recommendation is to download new extension. Closing this issue. cc: @itowlson
