### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by sandipchajjed** [Azure/vscode-aks-tools#54]
- Issue Type: `Bug`
- Extension Name: `vscode-aks-tools`
- Extension Version: `0.0.8`
- OS Version: `Darwin x64 20.3.0`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by sandipchajjed** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 22377,
		"activateCallTime": 0,
		"activateResolvedTime": 34,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "azuredevspaces.azds",
				"_lower": "azuredevspaces.azds"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by itowlson** [comment]
@Tatsinnit We should look at webpacking the extension as we now (finally!) do for the core extension.  Are you interested in looking at that or shall I do it - I know you have a lot on your plate right now.
