### ISSUE TITLE
Azure account login can get into a stuck state if you exit out of your request

### ISSUE THREAD

**Issue by qpetraroia** [Azure/vscode-aks-tools#639]
**Describe the bug**

The team is aware of a bug that is impacting the functionality of Azure login. We have reached out to the VS Code team and have opened an [issue](https://github.com/microsoft/vscode/issues/211406). Once this bug is fixed, we will close this issue.

**To Reproduce**
1. Login through AKS login
2. Go through the steps until your browser window pops up
3. Instead of signing in, exit your browser
4. Notice the stuck state - the AKS login command no longer works.

**Additional context**
To make sure you don't run into this bug, please continue through the entire login process without exiting. If you do experience this bug, please restart VS Code to fix.

**Comment by peterbom** [comment]
This is now fixed in VS Code.
