### ISSUE TITLE
'Log in' documentation

### ISSUE THREAD

**Issue by m-v-k** [Azure/vscode-aks-tools#7]
Took me a while to find a closed issue here explaining how to properly sign in.
please add this to some readme. 'how to use' or 'getting started'

**Comment by itowlson** [comment]
I think #6 addresses this at the UI level, but if it's still confusing after we ship that then I can definitely add some docs!

**Comment by itowlson** [comment]
Think #38 covers this, but happy for anyone to reopen it if the docs still don't give them what they need!
