### ISSUE TITLE
Support admin credentials

### ISSUE THREAD

**Issue by aelij** [Azure/vscode-aks-tools#70]
It can be useful to connect to an AKS cluster using `az aks get-credentials --admin`.
Please support it in the extension

**Comment by Tatsinnit** [comment]
💡 Thank you for this @aelij , I am not entirely sure scenario is underlying for adding `--admin` flag for this but this extension is child extension of : https://github.com/Azure/vscode-kubernetes-tools extension.

Might be worth to detail your scenario which you think will benefit having the `--admin` flag.

* Essentially here is what happens for `get-credentials`: https://github.com/Azure/vscode-kubernetes-tools/blob/master/src/components/clusterprovider/azure/azure.ts#L359 

Also might be worth to move it to the parent extension. 

Thank you 🙏

**Comment by aelij** [comment]
Thanks, @Tatsinnit. Could you maybe [transfer](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository#transferring-an-open-issue-to-another-repository) the issue? I don't have permissions :)

**Comment by Tatsinnit** [comment]
Update:

Hiya @aelij, just to keep you in loop, I am planning to scope some work for this and see if there is a way to handle it before we transfer.

Will keep you posted. Thank you so much. 🙏

**Comment by Tatsinnit** [comment]
💡 🕵️ Here is a possible idea / possible solution so I will share below as a note and will try it out sometime, if it is doable.

* Create the `shelljs` wrapper in this project for the `az command` here https://github.com/Azure/vscode-kubernetes-tools/blob/master/src/components/clusterprovider/azure/azure.ts#L359 
* Then, create sub-menu with another menu option called `Merge to Kubeconfig (Admin)` 
* Then, I guess some how use the `cluster explorer` API to make it appear in the `cluster explorer` with `(admin) alias` next to the cluster merges with `admin` permission option. 🔑 `Please Note`: **This part** is something I am not sure about and will explore once I will start the implementation.

Just as FYI mentioning here as Plan of action (which could work).

Thanks heaps, 🙏☕

**Comment by aelij** [comment]
This has become much less needed now that AKS supports Azure RBAC.
But there is another issue, with RBAC `kubectl` requires some form of interactive login, and it causes the plugin to get stuck loading the cluster tree.

**Comment by itowlson** [comment]
The cluster tree is a known issue in the `vscode-kubernetes-tools` extension (which this one builds on top of) and frankly I’m stumped on how to address it. The issue, as you’ve identified, is that we use kubectl to interact with k8s, including e.g. to get the list of known clusters; and in RBAC mode, kubectl pauses to prompt the user, and we can’t easily detect that, so we end up hanging forever.

I did some major rearchitecting of the CLI subsystem a year or two ago, with this as one of the things I wanted to lay the groundwork for fixing, but never quite cracked this issue.  Do feel free to hound me about it on the parent extension repo, and perhaps we can get a few more brains on it!

**Comment by aelij** [comment]
One small improvement that you could add - currently after it gets stuck, you have to restart VS Code. To fix it, I run kubectl manually, login interactively, then restart VS. It would be helpful if the extension would cancel the stuck kubectl command when clicking the refresh button instead of remaining stuck.

I'd also add a timeout for all kubectl commands.

**Comment by itowlson** [comment]
That might be an acceptable compromise, and at this point an acceptable compromise is better than leaving it as is while trying to figure out an ideal solution. Thanks for the suggestion!

**Comment by aelij** [comment]
I'm closing this issue as it's less important
