### ISSUE TITLE
Deprecation of starter workflows for Draft commands

### ISSUE THREAD

**Issue by qpetraroia** [Azure/vscode-aks-tools#707]
With the arrival of Draft in the AKS VS Code extension, the team will be removing and deprecating the starter workflows in the upcoming weeks. If you wish to generate starter workflows, please use the `Draft Create a GitHub Workflow` command. The starter workflows will continue to be in the AKS extension for the following month, with a removal after June 2024.

**Comment by hsubramanianaks** [comment]
This is released already. Closing it.
