### ISSUE TITLE
Draft Github Workflow does not populate repositories 

### ISSUE THREAD

**Issue by ReinierCC** [Azure/vscode-aks-tools#831]
**Describe the bug**
The window "Automated Deployments: Draft a GitHub Workflow" does not show the user's available repositories.

When the "Create Github Workflow" window is opened the extension attempts to retrieve the available repos but gets a 404 error instead.

**Mention the platform you are using**
AKS Extension v1.4.8

**To Reproduce**
1. Open VScode developer logs
2. Select "Create Github Workflow"

**Expected behavior**

Repos owned by the user should show under "GitHub repository *"

**Screenshots**

![image](https://github.com/user-attachments/assets/668432db-3281-4abc-9a81-6a678b372f7c)

![image](https://github.com/user-attachments/assets/6daa7707-5324-42f0-8471-122c9ff8dda4)

**Desktop (please complete the following information):**
- WSL:Ubuntu 

**Additional context**
Tested with both a forked repo and one that I own

**Comment by Tatsinnit** [comment]
Thanks @ReinierCC for this issue and details, let's definitely jump on a quick call and we should see what's happening under the hood. Or, whatever seems good. Thanks.

**Comment by ReinierCC** [comment]
https://github.com/Azure/vscode-aks-tools/pull/832
