### ISSUE TITLE
AKS Welcome page ALWAYS opens

### ISSUE THREAD

**Issue by Jaykul** [Azure/vscode-aks-tools#930]
**Describe the bug**

The AKS Extension (unlike **any** other extension I've used) keeps showing the welcome page every time I open VS Code, or open a new folder, regardless of the fact that there's no new news, and everything in there has been marked "Done". 

After the first dozen times a day it's actually quite annoying. See also: 
- https://github.com/microsoft/vscode/issues/212926
- https://github.com/microsoft/vscode/issues/112494
- https://github.com/alefragnani/vscode-bookmarks/issues/175

**Mention the platform you are using**

VSCode, Windows

**To Reproduce**

1. Install AKS Extension in VSCode
2. Open VS Code ("Welcome" shows)
   ![image](https://github.com/user-attachments/assets/53c210c8-a69f-4732-833b-fd2125968140)
3. Mark everything done ... 
2. Open VS Code ("Welcome" still shows)
3. Click to mark everything done ... again
4. Disable "Welcome" globally 
   ![image](https://github.com/user-attachments/assets/83c55a93-c46a-42ee-9756-41a3a0e27fed)
2. Open VS Code ("Welcome" still shows)

**Expected behavior**

1. Welcome pages should **only** show if I have "Show welcome page on startup"
2. Extension-specific welcome pages should **only** show if there's new information that's not marked done
3. Extension should register it's "Welcome" page in the command palette so I can open it later myself

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox

**Comment by Tatsinnit** [comment]
Thank you so much for reporting this, really appreciate it! We've added a fix for this, and once tested and merged it will be part of next release. Thanks. Thank you so much for repro @ReinierCC for testing as well.

**Comment by Tatsinnit** [comment]
💡A quick loop back, post release: the fix for this is released under version `1.4.10` thank you so much for this. ❤️ 🙏
